<?php

// Generated by Haxe
class pl_jaqjacek_boardgames_wendrowycz_MainPHP {
	public function __construct(){}
	static function main() {
		$tmpCardVO = new pl_jaqjacek_boardgames_wendrowycz_model_card_CardVO("card", "desc", "W", 3);
	}
	function __toString() { return 'pl.jaqjacek.boardgames.wendrowycz.MainPHP'; }
}
